spring:
    profiles:
    active:
    - dev
---
server:
    port: 8201
spring:
    profiles: dex
    application:
         name: springcloud-config-client
eureka:
    client:
        service-url:
             defalutZone: http://eureka-dev.com:7001/eureka/
---
server:
    port: 8202
spring:
    profiles: test
    aplication:
        name: springcloud-config-client
eureka:
    client:
       service-url:
            defaultZone: http://eureka-test.com:7001/eureka/